### ISSUE TITLE
hash type has no attribute value

### ISSUE THREAD

**Issue by ScanMountGoat** [BenHall-7/pyprc#1]
Running the example code on my end after installing pyprc with pip produces an error. 

The code as listed in the example:
```python
from pyprc import *

name = hash("fighter_kind_pzenigame")
print(name.value) # prints "0x16b9c57bd9"
hash.load_labels("ParamLabels.csv")
print(name.value) # prints "fighter_kind_pzenigame"
```
Error : `AttributeError: 'builtins.hash' object has no attribute 'value'`

Creating the type using param.hash works, but the formatting is slightly different.
```python
from pyprc import *

name = param.hash(hash("fighter_kind_pzenigame"))
print(name.value) # prints "hash (0x16b9c57bd9)"
hash.load_labels("ParamLabels.csv")
print(name.value) # prints "hash (fighter_kind_pzenigame")
```

**Comment by benhall-7** [comment]
I think I got ahead of myself there, I realized the other day that I didn't actually implement a method to return just the hash's value (`__str__` and `__repr__` will show `hash (xyz)`) but I forgot I had an example based on the notion. I should be able to have that implemented sometime late tomorrow

**Comment by benhall-7** [comment]
Fixed! New builds are uploaded to pypi
